-- Rider-Waite-Smith Tarot Deck for jongu-wellness
-- Run this in your Supabase SQL Editor

-- First, update the document_type constraint to include 'tarot_deck'
-- (Run this only if the constraint doesn't already include 'tarot_deck')

ALTER TABLE user_documents
DROP CONSTRAINT IF EXISTS user_documents_document_type_check;

ALTER TABLE user_documents
ADD CONSTRAINT user_documents_document_type_check
CHECK (document_type = ANY (ARRAY[
  'tool_session', 'creative_work', 'preference', 'bookmark',
  'interaction', 'transaction', 'story', 'playlist', 'tarot_deck'
]));

-- Insert the Rider-Waite-Smith Tarot deck
INSERT INTO user_documents (
  id,
  user_id,
  document_type,
  is_public,
  document_data,
  created_at,
  updated_at
)
VALUES (
  gen_random_uuid(),
  (SELECT id FROM auth.users LIMIT 1),
  'tarot_deck',
  true,
  '{
    "name": "Rider-Waite-Smith Archetypal Tarot",
    "description": "A 78-card tarot deck with archetypal, therapeutic interpretations for each card. This deck presents the classic Rider-Waite-Smith imagery with a focus on personal insight, reflection, and growth instead of fortune-telling predictions.",
    "creator_name": "Pamela Colman Smith",
    "cover_image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/RWS_Tarot_00_Fool.jpg",
    "card_count": 78,
    "tags": ["classic", "therapeutic", "archetypal", "full deck", "major arcana", "minor arcana"],
    "cards": [
      {
        "id": "rws-0",
        "name": "The Fool",
        "number": 0,
        "arcana": "major",
        "suit": null,
        "element": "Air",
        "keywords": ["innocence", "new beginnings", "free spirit"],
        "summary": "Symbolizes innocence and new beginnings – a free spirit embarking on the unknown.",
        "interpretation": "Upright, The Fool represents innocence, new beginnings and free spirit. In a therapeutic context, this card encourages you to embrace these qualities, using them as a source of strength and motivation for personal growth.",
        "reversed_interpretation": "Reversed, The Fool may signal recklessness, taken advantage of and inconsideration. Through a therapeutic lens, this reversal invites you to reflect on underlying causes and beliefs contributing to such impulsive behavior, so you can make more mindful choices going forward.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/RWS_Tarot_00_Fool.jpg",
        "affirmation": "I embrace new beginnings with courage and trust.",
        "questions": ["What new adventure is calling me?", "Where might I benefit from a fresh perspective?"],
        "sort_order": 0
      },
      {
        "id": "rws-1",
        "name": "The Magician",
        "number": 1,
        "arcana": "major",
        "suit": null,
        "element": "Air",
        "keywords": ["willpower", "desire", "creation", "manifestation"],
        "summary": "Symbolizes willpower, desire, and the ability to manifest one intentions into reality.",
        "interpretation": "Upright, The Magician represents willpower, desire, creation and manifestation. In a therapeutic context, this card encourages you to tap into your personal power and focus your intentions, recognizing that you have the tools to create positive change in your life.",
        "reversed_interpretation": "Reversed, The Magician may signal trickery, illusions and being out of touch. Through a therapeutic lens, this reversal invites you to examine where you may be deceiving yourself or feeling powerless, so you can ground yourself in honesty and regain a sense of control.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/RWS_Tarot_01_Magician.jpg",
        "affirmation": "I have all the tools I need to create my reality.",
        "questions": ["What resources do I already have?", "How can I focus my intentions more clearly?"],
        "sort_order": 1
      },
      {
        "id": "rws-2",
        "name": "The High Priestess",
        "number": 2,
        "arcana": "major",
        "suit": null,
        "element": "Water",
        "keywords": ["intuitive", "unconscious", "inner voice"],
        "summary": "Symbolizes intuition and the unconscious – the inner voice and hidden knowledge within.",
        "interpretation": "Upright, The High Priestess represents intuition, the unconscious and one inner voice. In a therapeutic context, this card encourages you to trust your gut feelings and pay attention to the subtle messages from your inner self, acknowledging the wisdom that comes from within.",
        "reversed_interpretation": "Reversed, The High Priestess may signal a lack of center, lost inner voice or repressed feelings. Through a therapeutic lens, this reversal invites you to explore what distractions or anxieties are drowning out your intuition, and to create space for your true feelings to surface and be understood.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/RWS_Tarot_02_High_Priestess.jpg",
        "affirmation": "I trust my inner wisdom and listen to my intuition.",
        "questions": ["What is my intuition telling me?", "What hidden knowledge needs to surface?"],
        "sort_order": 2
      },
      {
        "id": "rws-3",
        "name": "The Empress",
        "number": 3,
        "arcana": "major",
        "suit": null,
        "element": "Earth",
        "keywords": ["motherhood", "fertility", "nature"],
        "summary": "Symbolizes abundance, fertility, and nurturing – the creative, motherly energy of growth and prosperity.",
        "interpretation": "Upright, The Empress represents motherhood, fertility and nature. In a therapeutic context, this card encourages you to nurture yourself and others, fostering creativity and allowing abundance to grow in your life by caring for your physical and emotional needs.",
        "reversed_interpretation": "Reversed, The Empress may signal dependence, smothering, emptiness or nosiness. Through a therapeutic lens, this reversal invites you to consider where you might feel empty or overbearing – and to cultivate healthy independence and self-care, rather than seeking validation solely from others.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/RWS_Tarot_03_Empress.jpg",
        "affirmation": "I nurture myself and others with abundant love.",
        "questions": ["How can I better nurture myself?", "What creative projects need my attention?"],
        "sort_order": 3
      },
      {
        "id": "rws-4",
        "name": "The Emperor",
        "number": 4,
        "arcana": "major",
        "suit": null,
        "element": "Fire",
        "keywords": ["authority", "structure", "control", "fatherhood"],
        "summary": "Symbolizes authority, structure, and control – the fatherly influence of stability and responsibility.",
        "interpretation": "Upright, The Emperor represents authority, structure, control and fatherhood. In a therapeutic context, this card encourages you to develop healthy boundaries and self-discipline, stepping into your own authority over your life while balancing firmness with compassion.",
        "reversed_interpretation": "Reversed, The Emperor may signal tyranny, rigidity or coldness. Through a therapeutic lens, this reversal invites you to examine issues with control or inflexibility in your life – possibly a tendency to be too harsh on yourself or others – and to work on introducing understanding and flexibility where it is needed.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/RWS_Tarot_04_Emperor.jpg",
        "affirmation": "I create healthy structures that support my growth.",
        "questions": ["Where do I need more structure?", "Am I being too rigid or too lenient?"],
        "sort_order": 4
      },
      {
        "id": "rws-5",
        "name": "The Hierophant",
        "number": 5,
        "arcana": "major",
        "suit": null,
        "element": "Earth",
        "keywords": ["tradition", "conformity", "morality", "ethics"],
        "summary": "Symbolizes tradition, spirituality, and guidance – values, ethics, and the wisdom of collective teachings.",
        "interpretation": "Upright, The Hierophant represents tradition, conformity, morality and ethics. In a therapeutic context, this card encourages you to explore your belief systems and values – understanding the family or cultural traditions that shaped you – and to seek wise counsel or mentorship when needed.",
        "reversed_interpretation": "Reversed, The Hierophant may signal rebellion, subversiveness or new approaches. Through a therapeutic lens, this reversal invites you to question outdated beliefs and find your own authentic path. It suggests that breaking from convention can be healthy if your current norms no longer serve your personal growth.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/RWS_Tarot_05_Hierophant.jpg",
        "affirmation": "I honor wisdom while finding my own path.",
        "questions": ["What traditions serve me well?", "What beliefs need to be questioned?"],
        "sort_order": 5
      },
      {
        "id": "rws-6",
        "name": "The Lovers",
        "number": 6,
        "arcana": "major",
        "suit": null,
        "element": "Air",
        "keywords": ["partnerships", "duality", "union"],
        "summary": "Symbolizes love, union, and choice – the harmony and duality in partnerships and values.",
        "interpretation": "Upright, The Lovers represents partnerships, duality and union. In a therapeutic context, this card encourages you to explore how you form relationships and make heartfelt choices – aligning decisions with your values and fostering healthy bonds built on honest communication and mutual respect.",
        "reversed_interpretation": "Reversed, The Lovers may signal a loss of balance, one-sidedness or disharmony. Through a therapeutic lens, this reversal invites you to address imbalances in your relationships or inner conflicts in your values, working to restore honesty, self-love and harmony between the parts of your life that feel disconnected.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/RWS_Tarot_06_Lovers.jpg",
        "affirmation": "I make choices aligned with my deepest values.",
        "questions": ["What choice am I facing?", "Are my relationships in balance?"],
        "sort_order": 6
      },
      {
        "id": "rws-7",
        "name": "The Chariot",
        "number": 7,
        "arcana": "major",
        "suit": null,
        "element": "Water",
        "keywords": ["direction", "control", "willpower"],
        "summary": "Symbolizes willpower, direction, and victory – harnessing inner drive to overcome obstacles.",
        "interpretation": "Upright, The Chariot represents direction, control and willpower. In a therapeutic context, this card encourages you to harness your determination and emotional balance to move forward. It suggests focusing on your goals and confidently steering through challenges by managing conflicting impulses within.",
        "reversed_interpretation": "Reversed, The Chariot may signal a lack of control, lack of direction or aggression. Through a therapeutic lens, this reversal invites you to examine where you feel pulled in opposing directions or stuck. It is a reminder to regroup and clarify your goals, addressing inner conflicts or anxieties so you can regain a sense of direction.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/RWS_Tarot_07_Chariot.jpg",
        "affirmation": "I move forward with determination and focus.",
        "questions": ["What is driving me forward?", "How can I better manage opposing forces in my life?"],
        "sort_order": 7
      },
      {
        "id": "rws-8",
        "name": "Strength",
        "number": 8,
        "arcana": "major",
        "suit": null,
        "element": "Fire",
        "keywords": ["inner strength", "bravery", "compassion", "focus"],
        "summary": "Symbolizes inner strength, compassion, and courage – gentle resilience taming the inner beast.",
        "interpretation": "Upright, Strength represents inner strength, bravery, compassion and focus. In a therapeutic context, this card encourages you to approach your challenges with patience and love. It highlights that true strength often lies in compassionate self-control – calming your inner critic or raw emotions with understanding rather than force.",
        "reversed_interpretation": "Reversed, Strength may signal self-doubt, weakness or insecurity. Through a therapeutic lens, this reversal invites you to acknowledge vulnerabilities without judgment. It suggests working on rebuilding confidence by treating yourself kindly, and remembering past instances of resilience to counter feelings of inadequacy.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/RWS_Tarot_08_Strength.jpg",
        "affirmation": "My gentleness is my greatest strength.",
        "questions": ["Where do I need more compassion for myself?", "What inner beast needs taming with love?"],
        "sort_order": 8
      },
      {
        "id": "rws-9",
        "name": "The Hermit",
        "number": 9,
        "arcana": "major",
        "suit": null,
        "element": "Earth",
        "keywords": ["contemplation", "search for truth", "inner guidance"],
        "summary": "Symbolizes introspection, wisdom, and guidance – the quest for truth through solitude and self-reflection.",
        "interpretation": "Upright, The Hermit represents contemplation, a search for truth and inner guidance. In a therapeutic context, this card encourages you to take time for yourself – to step back from the noise and reflect inward. It suggests that solitude and introspection can provide the insight or answers you seek at this stage of your journey.",
        "reversed_interpretation": "Reversed, The Hermit may signal loneliness, isolation or feeling lost. Through a therapeutic lens, this reversal invites you to reach out and reconnect where you have withdrawn too far. It is a reminder that while introspection is valuable, support from others and sharing your experience is equally important when you feel adrift.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/RWS_Tarot_09_Hermit.jpg",
        "affirmation": "I carry my own light into the darkness.",
        "questions": ["What truth am I seeking?", "Do I need solitude or connection right now?"],
        "sort_order": 9
      },
      {
        "id": "rws-10",
        "name": "Wheel of Fortune",
        "number": 10,
        "arcana": "major",
        "suit": null,
        "element": "Fire",
        "keywords": ["change", "cycles", "inevitable fate"],
        "summary": "Symbolizes life cycles and change – the turning point of fate inviting adaptation and acceptance.",
        "interpretation": "Upright, the Wheel of Fortune represents change, cycles and inevitable fate. In a therapeutic context, this card encourages you to recognize what is within your control and what is not. It invites acceptance of life ups and downs, reminding you that difficult times give way to better ones, and that adaptability and resilience are key as circumstances evolve.",
        "reversed_interpretation": "Reversed, the Wheel of Fortune may signal feeling no control, clinging to control or bad luck. Through a therapeutic lens, this reversal invites you to examine your resistance to change. It suggests working on letting go of the need to control every outcome, and reframing setbacks not as personal failures but as temporary phases that you have the strength to get through.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/RWS_Tarot_10_Wheel_of_Fortune.jpg",
        "affirmation": "I surrender to the wisdom of life cycles.",
        "questions": ["What cycle is turning in my life?", "What am I resisting that I cannot control?"],
        "sort_order": 10
      },
      {
        "id": "rws-11",
        "name": "Justice",
        "number": 11,
        "arcana": "major",
        "suit": null,
        "element": "Air",
        "keywords": ["cause and effect", "clarity", "truth"],
        "summary": "Symbolizes fairness, truth, and accountability – the moral balance of cause and effect in one life.",
        "interpretation": "Upright, Justice represents cause and effect, clarity and truth. In a therapeutic context, this card encourages you to take accountability for your actions and to seek truth in your situation. It highlights the importance of honest self-reflection and making amends or adjustments to restore balance and fairness in your life where needed.",
        "reversed_interpretation": "Reversed, Justice may signal dishonesty, unaccountability or unfairness. Through a therapeutic lens, this reversal invites you to consider where you might feel treated unjustly or where you might be avoiding responsibility. It suggests working towards honesty with yourself and others, and understanding that healing often requires addressing imbalances or wrongs rather than ignoring them.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/RWS_Tarot_11_Justice.jpg",
        "affirmation": "I see myself and my situation clearly, with compassion and honesty.",
        "questions": ["What truth am I avoiding?", "Where is balance needed in my life?"],
        "sort_order": 11
      },
      {
        "id": "rws-12",
        "name": "The Hanged Man",
        "number": 12,
        "arcana": "major",
        "suit": null,
        "element": "Water",
        "keywords": ["sacrifice", "release", "martyrdom"],
        "summary": "Symbolizes sacrifice, surrender, and a new perspective – a pause for insight by releasing control.",
        "interpretation": "Upright, The Hanged Man represents sacrifice, release and martyrdom (a willingness to let go). In a therapeutic context, this card encourages you to pause and allow a change of perspective. It suggests that by surrendering your usual approach or need for control, you can gain fresh insight into a problem – turning what feels like a setback into an opportunity for growth.",
        "reversed_interpretation": "Reversed, The Hanged Man may signal stalling, needless sacrifice or fear of sacrifice. Through a therapeutic lens, this reversal invites you to examine where you feel stuck or unable to let go of an old pattern. It is a reminder that clinging too tightly out of fear can prevent progress – and that learning to release or see things differently, though uncomfortable, might be exactly what is needed to move forward.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/RWS_Tarot_12_Hanged_Man.jpg",
        "affirmation": "I surrender to the wisdom of not-doing.",
        "questions": ["What would happen if I stopped trying so hard?", "What perspective shift do I need?"],
        "sort_order": 12
      },
      {
        "id": "rws-13",
        "name": "Death",
        "number": 13,
        "arcana": "major",
        "suit": null,
        "element": "Water",
        "keywords": ["end of cycle", "beginnings", "change", "metamorphosis"],
        "summary": "Symbolizes transformation, endings, and rebirth – the closing of one chapter to allow new growth.",
        "interpretation": "Upright, Death represents the end of a cycle, beginnings, change and metamorphosis. In a therapeutic context, this card encourages you to embrace necessary endings (such as the end of a habit, phase, or relationship) as a natural part of growth. It signifies that by processing the loss and letting go of what no longer serves you, you create space for new opportunities and personal transformation.",
        "reversed_interpretation": "Reversed, Death may signal fear of change, holding on, stagnation or decay. Through a therapeutic lens, this reversal invites you to explore what fears are keeping you stuck in an unhealthy status quo. It suggests gently confronting your resistance to change, perhaps with support, and reframing endings not as something to dread but as transitions that can lead to renewal.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/RWS_Tarot_13_Death.jpg",
        "affirmation": "I release what has ended so new life can begin.",
        "questions": ["What is ready to end in my life?", "What new life is waiting to be born?"],
        "sort_order": 13
      },
      {
        "id": "rws-14",
        "name": "Temperance",
        "number": 14,
        "arcana": "major",
        "suit": null,
        "element": "Fire",
        "keywords": ["middle path", "patience", "finding meaning"],
        "summary": "Symbolizes balance, moderation, and healing – finding the middle path through patience and integration.",
        "interpretation": "Upright, Temperance represents the middle path, patience and finding meaning through balance. In a therapeutic context, this card encourages you to practice moderation and to blend different aspects of your life or personality harmoniously. It suggests that healing often comes from integrating opposites (like work and rest, or emotion and reason) and taking a measured, patient approach rather than all-or-nothing thinking.",
        "reversed_interpretation": "Reversed, Temperance may signal extremes, excess or lack of balance. Through a therapeutic lens, this reversal invites you to identify areas where you may be overindulging or swinging between extremes. It is a call to bring yourself back to center – perhaps by establishing routines, setting healthy boundaries, or seeking a calmer middle ground – in order to restore equilibrium and peace of mind.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/RWS_Tarot_14_Temperance.jpg",
        "affirmation": "I blend all parts of myself into harmonious flow.",
        "questions": ["Where do I need more balance?", "What extremes need to be integrated?"],
        "sort_order": 14
      },
      {
        "id": "rws-15",
        "name": "The Devil",
        "number": 15,
        "arcana": "major",
        "suit": null,
        "element": "Earth",
        "keywords": ["addiction", "materialism", "playfulness"],
        "summary": "Symbolizes temptation, attachment, and the shadow self – the material or emotional chains that can bind one.",
        "interpretation": "Upright, The Devil acknowledges themes of addiction, materialism and playfulness (worldly indulgence). From a therapeutic perspective, this card encourages you to face and work through these shadow aspects with patience and self-compassion. It asks you to recognize the habits or thought patterns that keep you feeling trapped – such as dependencies or negative self-talk – and to understand why they hold appeal, as a first step to regaining your power over them.",
        "reversed_interpretation": "Reversed, The Devil can indicate freedom, release and restoring control. When this card appears reversed, it suggests an opportunity for relief and positive change. Therapeutically, it points to a phase of breaking free – perhaps you are beginning to overcome an addiction, leave a toxic situation, or reclaim your autonomy. It urges you to continue letting go of old, limiting patterns and to embrace this newfound sense of empowerment and freedom.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/RWS_Tarot_15_Devil.jpg",
        "affirmation": "I embrace my shadow as a source of hidden wisdom and power.",
        "questions": ["What have I disowned in myself?", "What chains am I ready to break?"],
        "sort_order": 15
      },
      {
        "id": "rws-16",
        "name": "The Tower",
        "number": 16,
        "arcana": "major",
        "suit": null,
        "element": "Fire",
        "keywords": ["sudden upheaval", "broken pride", "disaster"],
        "summary": "Symbolizes sudden upheaval and revelation – the collapse of false structures leading to profound change.",
        "interpretation": "Upright, The Tower represents sudden upheaval, a broken sense of pride and disaster (a rapid, unexpected change). In a therapeutic context, this card encourages you to understand that sometimes a dramatic shake-up can reveal truths that were hidden. It acknowledges the pain and shock of sudden change, yet also suggests that this breakdown can clear the way for more authentic growth once the dust settles. The focus is on finding stability within yourself when external stability crumbles.",
        "reversed_interpretation": "Reversed, The Tower may signal a disaster avoided, delayed disaster or fear of suffering. Through a therapeutic lens, this reversal invites you to explore your fear of inevitable change – are you trying to prevent the unpreventable, or clinging to something that needs to fall apart? It suggests that while you might postpone the confrontation, true healing will come from facing the situation honestly.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/RWS_Tarot_16_Tower.jpg",
        "affirmation": "I welcome the storms that set me free from false structures.",
        "questions": ["What false structure is ready to fall?", "How can I find stability within myself?"],
        "sort_order": 16
      },
      {
        "id": "rws-17",
        "name": "The Star",
        "number": 17,
        "arcana": "major",
        "suit": null,
        "element": "Air",
        "keywords": ["hope", "faith", "rejuvenation"],
        "summary": "Symbolizes hope, faith, and renewal – a calm optimism and guiding light after the storm.",
        "interpretation": "Upright, The Star represents hope, faith and rejuvenation. In a therapeutic context, this card encourages you to nurture optimism and trust in the healing process. It is the gentle reminder that after hardship (the Tower chaos), there is an opportunity for renewal – a chance to replenish your spirit, believe in yourself, and envision a positive future. This card invites you to engage in activities that restore you and to remain open to inspiration.",
        "reversed_interpretation": "Reversed, The Star may signal faithlessness, discouragement or insecurity. Through a therapeutic lens, this reversal invites you to acknowledge feelings of hopelessness or low self-esteem that may be weighing on you. It suggests working to reconnect with sources of inspiration and support. By identifying small glimmers of hope and practicing gratitude or self-care, you can slowly rebuild your sense of faith in yourself and in better days ahead.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/RWS_Tarot_17_Star.jpg",
        "affirmation": "I drink from the eternal spring of hope and healing.",
        "questions": ["What replenishes my soul?", "Am I allowing myself to heal?"],
        "sort_order": 17
      },
      {
        "id": "rws-18",
        "name": "The Moon",
        "number": 18,
        "arcana": "major",
        "suit": null,
        "element": "Water",
        "keywords": ["unconscious", "illusions", "intuition"],
        "summary": "Symbolizes intuition, illusion, and the subconscious – the realm of dreams, fears, and unseen depth.",
        "interpretation": "Upright, The Moon represents the unconscious, illusions and intuition. In a therapeutic context, this card encourages you to explore the deeper, less conscious parts of your psyche – such as your dreams, fears, and intuitions. It acknowledges that not everything is clear or rational, and that is okay. This card invites you to sit with uncertainty, listen to your intuition, and perhaps use creative or reflective practices (like journaling, art, or therapy itself) to understand the undercurrents of your emotions without fear.",
        "reversed_interpretation": "Reversed, The Moon may signal confusion, fear or misinterpretation. Through a therapeutic lens, this reversal invites you to address the anxieties or misconceptions that may be clouding your perception. It suggests grounding techniques – like reality-testing your fears or talking them through with someone you trust – to dispel the shadows of doubt. By bringing these fears from darkness into light, you can reduce their power over you.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/RWS_Tarot_18_Moon.jpg",
        "affirmation": "I navigate the mysterious depths with my inner knowing as my guide.",
        "questions": ["What fears are distorting my perception?", "What lies in the depths I have not explored?"],
        "sort_order": 18
      },
      {
        "id": "rws-19",
        "name": "The Sun",
        "number": 19,
        "arcana": "major",
        "suit": null,
        "element": "Fire",
        "keywords": ["joy", "success", "celebration", "positivity"],
        "summary": "Symbolizes joy, vitality, and optimism – the illumination of truth, success, and youthful energy.",
        "interpretation": "Upright, The Sun represents joy, success, celebration and positivity. In a therapeutic context, this card encourages you to embrace your authentic self and celebrate your achievements, no matter how small. It highlights the healing power of positivity and transparency – being open and childlike in your approach to life pleasures. The Sun invites you to step out of the shadows of doubt and into a place of warmth, confidence, and clarity about who you are.",
        "reversed_interpretation": "Reversed, The Sun may signal negativity, depression or sadness. Through a therapeutic lens, this reversal invites you to compassionately address any lingering sadness or pessimism. It suggests that even when you cannot feel the sunshine, it is still there – meaning there are positive aspects in your life to rediscover. Work on challenging negative thoughts and letting your inner child have moments of play to gradually return to a sunnier outlook.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/RWS_Tarot_19_Sun.jpg",
        "affirmation": "I shine with the joy of being fully alive.",
        "questions": ["Where is authentic joy available to me?", "What dims my natural radiance?"],
        "sort_order": 19
      },
      {
        "id": "rws-20",
        "name": "Judgement",
        "number": 20,
        "arcana": "major",
        "suit": null,
        "element": "Fire",
        "keywords": ["reflection", "reckoning", "awakening"],
        "summary": "Symbolizes awakening, reckoning, and rebirth – a call to evaluate the past and renew one purpose.",
        "interpretation": "Upright, Judgement represents reflection, reckoning and awakening. In a therapeutic context, this card encourages you to engage in honest self-evaluation. It is about reviewing where you have been and what you have learned, forgiving yourself and others, and using that understanding to make a positive fresh start. Judgement heralds a rebirth of sorts – an opportunity to take accountability for the past while not being defined by it, and to move forward with a clearer, more enlightened sense of purpose.",
        "reversed_interpretation": "Reversed, Judgement may signal a lack of self-awareness, doubt or self-loathing. Through a therapeutic lens, this reversal invites you to confront harsh self-judgments or a fear of change that may be holding you back. It suggests that you might be ignoring an inner calling or undervaluing your worth due to guilt or doubt. Working through these feelings can help you break free of stagnation.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/RWS_Tarot_20_Judgement.jpg",
        "affirmation": "I hear my soul calling and I rise to answer it.",
        "questions": ["What is my soul calling me to become?", "What part of me is ready to rise?"],
        "sort_order": 20
      },
      {
        "id": "rws-21",
        "name": "The World",
        "number": 21,
        "arcana": "major",
        "suit": null,
        "element": "Earth",
        "keywords": ["fulfillment", "harmony", "completion"],
        "summary": "Symbolizes completion, wholeness, and fulfillment – the end of a journey and integration of lessons.",
        "interpretation": "Upright, The World represents fulfillment, harmony and completion. In a therapeutic context, this card encourages you to acknowledge and honor the completion of a significant cycle or achievement in your life. It signifies a sense of wholeness that comes from integrating all aspects of yourself and your experiences. Take a moment to celebrate how far you have come and to embrace the sense of closure and accomplishment.",
        "reversed_interpretation": "Reversed, The World may signal incompletion, shortcuts or a lack of closure. Through a therapeutic lens, this reversal invites you to examine what might be preventing you from feeling whole or complete. Perhaps there are loose ends to tie up or lessons yet to be fully integrated. It suggests taking time to address unfinished business before moving on to new beginnings.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/RWS_Tarot_21_World.jpg",
        "affirmation": "I celebrate the wholeness of my journey, complete in this moment.",
        "questions": ["What cycle is completing?", "How am I whole right now?"],
        "sort_order": 21
      },
      {
        "id": "rws-22",
        "name": "Ace of Wands",
        "number": 1,
        "arcana": "minor",
        "suit": "wands",
        "element": "Fire",
        "keywords": ["creation", "willpower", "inspiration", "desire"],
        "summary": "A spark of creative inspiration and new beginnings in passion, career, or personal projects.",
        "interpretation": "Upright, Ace of Wands represents creation, willpower, inspiration and desire. In a therapeutic context, this card encourages you to seize the creative spark that is presenting itself. It is an invitation to begin something new with passion and enthusiasm – whether a project, relationship, or personal transformation.",
        "reversed_interpretation": "Reversed, Ace of Wands may signal delays, lack of motivation or creative blocks. Through a therapeutic lens, this reversal invites you to explore what is dampening your enthusiasm or blocking your creative flow. Perhaps fear of failure or external pressures are holding you back from pursuing your passions.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Wands01.jpg",
        "affirmation": "I embrace the creative fire within me.",
        "questions": ["What new passion is emerging?", "What is blocking my creative energy?"],
        "sort_order": 22
      },
      {
        "id": "rws-23",
        "name": "Two of Wands",
        "number": 2,
        "arcana": "minor",
        "suit": "wands",
        "element": "Fire",
        "keywords": ["planning", "making decisions", "leaving comfort zone"],
        "summary": "Standing at a crossroads, contemplating future possibilities and the courage to venture forth.",
        "interpretation": "Upright, Two of Wands represents planning, making decisions and leaving your comfort zone. In a therapeutic context, this card encourages you to envision your future and make plans to pursue your goals. It suggests you have the power to shape your destiny.",
        "reversed_interpretation": "Reversed, Two of Wands may signal fear of the unknown, lack of planning or playing it safe. Through a therapeutic lens, this reversal invites you to examine what fears are keeping you in your comfort zone and preventing you from pursuing your vision.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Wands02.jpg",
        "affirmation": "I plan my future with confidence and courage.",
        "questions": ["What future am I envisioning?", "What is keeping me from taking the next step?"],
        "sort_order": 23
      },
      {
        "id": "rws-24",
        "name": "Three of Wands",
        "number": 3,
        "arcana": "minor",
        "suit": "wands",
        "element": "Fire",
        "keywords": ["expansion", "foresight", "overseas opportunities"],
        "summary": "Looking toward the horizon with anticipation as plans begin to take shape and expand.",
        "interpretation": "Upright, Three of Wands represents expansion, foresight and overseas opportunities. In a therapeutic context, this card encourages you to look beyond your immediate circumstances and consider broader possibilities. Your efforts are beginning to bear fruit.",
        "reversed_interpretation": "Reversed, Three of Wands may signal obstacles to success, delays in plans or lack of foresight. Through a therapeutic lens, this reversal invites you to reassess your plans and consider what obstacles might be hindering your progress.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Wands03.jpg",
        "affirmation": "I expand my horizons with confidence.",
        "questions": ["What opportunities lie ahead?", "What obstacles need addressing?"],
        "sort_order": 24
      },
      {
        "id": "rws-25",
        "name": "Four of Wands",
        "number": 4,
        "arcana": "minor",
        "suit": "wands",
        "element": "Fire",
        "keywords": ["celebration", "harmony", "homecoming"],
        "summary": "A time of celebration, community, and the joy of reaching a milestone.",
        "interpretation": "Upright, Four of Wands represents celebration, harmony and homecoming. In a therapeutic context, this card encourages you to celebrate your achievements and enjoy the stability you have created. It is a time to appreciate community and belonging.",
        "reversed_interpretation": "Reversed, Four of Wands may signal lack of harmony, broken homes or instability. Through a therapeutic lens, this reversal invites you to address any instability in your home life or community connections.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Wands04.jpg",
        "affirmation": "I celebrate my achievements and connections.",
        "questions": ["What am I celebrating?", "Where do I feel at home?"],
        "sort_order": 25
      },
      {
        "id": "rws-26",
        "name": "Five of Wands",
        "number": 5,
        "arcana": "minor",
        "suit": "wands",
        "element": "Fire",
        "keywords": ["competition", "conflict", "diversity"],
        "summary": "Navigating competition and conflict while learning to work with diverse perspectives.",
        "interpretation": "Upright, Five of Wands represents competition, conflict and diversity. In a therapeutic context, this card encourages you to see conflict as an opportunity for growth rather than just struggle. Healthy competition can sharpen your skills.",
        "reversed_interpretation": "Reversed, Five of Wands may signal avoiding conflict, diversity acceptance or ending of struggle. Through a therapeutic lens, this reversal invites you to find ways to resolve conflicts and move toward collaboration.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Wands05.jpg",
        "affirmation": "I navigate conflict with grace and learn from competition.",
        "questions": ["What conflict needs resolution?", "How can competition help me grow?"],
        "sort_order": 26
      },
      {
        "id": "rws-27",
        "name": "Six of Wands",
        "number": 6,
        "arcana": "minor",
        "suit": "wands",
        "element": "Fire",
        "keywords": ["victory", "success", "public recognition"],
        "summary": "Achievement and recognition for your efforts – a moment of triumph and acclaim.",
        "interpretation": "Upright, Six of Wands represents victory, success and public recognition. In a therapeutic context, this card encourages you to accept recognition for your achievements and to feel proud of your accomplishments.",
        "reversed_interpretation": "Reversed, Six of Wands may signal lack of recognition, failed achievement or fall from grace. Through a therapeutic lens, this reversal invites you to examine your relationship with external validation and find internal sources of self-worth.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Wands06.jpg",
        "affirmation": "I accept recognition for my achievements with grace.",
        "questions": ["What achievements deserve recognition?", "Am I seeking too much external validation?"],
        "sort_order": 27
      },
      {
        "id": "rws-28",
        "name": "Seven of Wands",
        "number": 7,
        "arcana": "minor",
        "suit": "wands",
        "element": "Fire",
        "keywords": ["challenge", "perseverance", "maintaining control"],
        "summary": "Standing your ground and defending your position against challenges and opposition.",
        "interpretation": "Upright, Seven of Wands represents challenge, perseverance and maintaining control. In a therapeutic context, this card encourages you to stand firm in your convictions and defend what you have worked for.",
        "reversed_interpretation": "Reversed, Seven of Wands may signal giving up, being overwhelmed or yielding to competition. Through a therapeutic lens, this reversal invites you to assess whether your battles are worth fighting and when it might be wise to step back.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Wands07.jpg",
        "affirmation": "I stand firm in my convictions.",
        "questions": ["What am I defending?", "Is this battle worth fighting?"],
        "sort_order": 28
      },
      {
        "id": "rws-29",
        "name": "Eight of Wands",
        "number": 8,
        "arcana": "minor",
        "suit": "wands",
        "element": "Fire",
        "keywords": ["speed", "action", "air travel", "movement"],
        "summary": "Rapid movement and swift action – things are accelerating and events unfold quickly.",
        "interpretation": "Upright, Eight of Wands represents speed, action and movement. In a therapeutic context, this card encourages you to act quickly and decisively while the momentum is in your favor. Things are moving fast.",
        "reversed_interpretation": "Reversed, Eight of Wands may signal delays, frustration or holding off. Through a therapeutic lens, this reversal invites you to practice patience when things are not moving as quickly as you would like.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Wands08.jpg",
        "affirmation": "I move swiftly toward my goals.",
        "questions": ["What is accelerating in my life?", "Where do I need to act quickly?"],
        "sort_order": 29
      },
      {
        "id": "rws-30",
        "name": "Nine of Wands",
        "number": 9,
        "arcana": "minor",
        "suit": "wands",
        "element": "Fire",
        "keywords": ["resilience", "grit", "last stand"],
        "summary": "Persevering through challenges with resilience – weary but still standing strong.",
        "interpretation": "Upright, Nine of Wands represents resilience, grit and last stand. In a therapeutic context, this card encourages you to keep going despite feeling weary. You have come too far to give up now.",
        "reversed_interpretation": "Reversed, Nine of Wands may signal giving up, exhaustion or stubbornness. Through a therapeutic lens, this reversal invites you to assess whether you are pushing yourself too hard and need to rest.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Wands09.jpg",
        "affirmation": "I persevere with resilience and strength.",
        "questions": ["What am I persevering through?", "Do I need rest or renewal?"],
        "sort_order": 30
      },
      {
        "id": "rws-31",
        "name": "Ten of Wands",
        "number": 10,
        "arcana": "minor",
        "suit": "wands",
        "element": "Fire",
        "keywords": ["burden", "extra responsibility", "hard work"],
        "summary": "Carrying a heavy load of responsibilities – the weight of success and its demands.",
        "interpretation": "Upright, Ten of Wands represents burden, extra responsibility and hard work. In a therapeutic context, this card encourages you to examine whether you are taking on too much and to consider delegating or releasing some burdens.",
        "reversed_interpretation": "Reversed, Ten of Wands may signal inability to delegate, overstressed or giving up. Through a therapeutic lens, this reversal invites you to learn to share your load and set healthier boundaries.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Wands10.jpg",
        "affirmation": "I release burdens that are not mine to carry.",
        "questions": ["What burdens can I release?", "Am I taking on too much?"],
        "sort_order": 31
      },
      {
        "id": "rws-32",
        "name": "Page of Wands",
        "number": 11,
        "arcana": "minor",
        "suit": "wands",
        "element": "Fire",
        "keywords": ["exploration", "excitement", "freedom"],
        "summary": "Youthful enthusiasm and a thirst for adventure – ready to explore new possibilities.",
        "interpretation": "Upright, Page of Wands represents exploration, excitement and freedom. In a therapeutic context, this card encourages you to embrace your curiosity and explore new interests with enthusiasm.",
        "reversed_interpretation": "Reversed, Page of Wands may signal lack of direction, procrastination or lack of passion. Through a therapeutic lens, this reversal invites you to reconnect with what excites you and reignite your passion.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Wands11.jpg",
        "affirmation": "I explore life with enthusiasm and curiosity.",
        "questions": ["What new adventure calls to me?", "How can I reignite my passion?"],
        "sort_order": 32
      },
      {
        "id": "rws-33",
        "name": "Knight of Wands",
        "number": 12,
        "arcana": "minor",
        "suit": "wands",
        "element": "Fire",
        "keywords": ["action", "adventure", "fearlessness"],
        "summary": "Charging forward with passion and courage – the adventurer ready to take action.",
        "interpretation": "Upright, Knight of Wands represents action, adventure and fearlessness. In a therapeutic context, this card encourages you to take bold action and pursue your goals with passion and courage.",
        "reversed_interpretation": "Reversed, Knight of Wands may signal haste, scattered energy or delays. Through a therapeutic lens, this reversal invites you to slow down and focus your energy more effectively.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Wands12.jpg",
        "affirmation": "I take bold action toward my dreams.",
        "questions": ["Where do I need to be bolder?", "Am I scattering my energy?"],
        "sort_order": 33
      },
      {
        "id": "rws-34",
        "name": "Queen of Wands",
        "number": 13,
        "arcana": "minor",
        "suit": "wands",
        "element": "Fire",
        "keywords": ["courage", "determination", "joy"],
        "summary": "Radiant confidence and warm-hearted leadership – inspiring others through passionate presence.",
        "interpretation": "Upright, Queen of Wands represents courage, determination and joy. In a therapeutic context, this card encourages you to embrace your confidence and use your charisma to inspire and lead others.",
        "reversed_interpretation": "Reversed, Queen of Wands may signal selfishness, jealousy or demanding. Through a therapeutic lens, this reversal invites you to examine whether your confidence has become overbearing or if insecurity is masked as arrogance.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Wands13.jpg",
        "affirmation": "I lead with confidence and inspire with joy.",
        "questions": ["How can I inspire others?", "Is my confidence balanced with humility?"],
        "sort_order": 34
      },
      {
        "id": "rws-35",
        "name": "King of Wands",
        "number": 14,
        "arcana": "minor",
        "suit": "wands",
        "element": "Fire",
        "keywords": ["big picture", "leader", "overcoming challenges"],
        "summary": "Visionary leadership and entrepreneurial spirit – seeing the big picture and inspiring action.",
        "interpretation": "Upright, King of Wands represents big picture thinking, leadership and overcoming challenges. In a therapeutic context, this card encourages you to take charge of your life with vision and inspire others through your example.",
        "reversed_interpretation": "Reversed, King of Wands may signal impulsiveness, haste or ruthless behavior. Through a therapeutic lens, this reversal invites you to temper your drive with patience and consider the impact of your actions on others.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Wands14.jpg",
        "affirmation": "I lead with vision and inspire through action.",
        "questions": ["What is my larger vision?", "Am I leading with integrity?"],
        "sort_order": 35
      },
      {
        "id": "rws-36",
        "name": "Ace of Cups",
        "number": 1,
        "arcana": "minor",
        "suit": "cups",
        "element": "Water",
        "keywords": ["new feelings", "spirituality", "intuition"],
        "summary": "The beginning of emotional fulfillment – an overflowing cup of love and spiritual connection.",
        "interpretation": "Upright, Ace of Cups represents new feelings, spirituality and intuition. In a therapeutic context, this card encourages you to open your heart to new emotional experiences and spiritual connections.",
        "reversed_interpretation": "Reversed, Ace of Cups may signal emotional loss, blocked creativity or emptiness. Through a therapeutic lens, this reversal invites you to address emotional blockages that are preventing you from feeling fulfilled.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Cups01.jpg",
        "affirmation": "I open my heart to love and emotional fulfillment.",
        "questions": ["What new feelings are emerging?", "How can I open my heart more?"],
        "sort_order": 36
      },
      {
        "id": "rws-37",
        "name": "Two of Cups",
        "number": 2,
        "arcana": "minor",
        "suit": "cups",
        "element": "Water",
        "keywords": ["unity", "partnership", "connection"],
        "summary": "Meaningful connection and partnership – two hearts joining in mutual understanding and love.",
        "interpretation": "Upright, Two of Cups represents unity, partnership and connection. In a therapeutic context, this card encourages you to cultivate meaningful relationships built on mutual respect and understanding.",
        "reversed_interpretation": "Reversed, Two of Cups may signal broken communication, imbalance or separation. Through a therapeutic lens, this reversal invites you to address relationship imbalances and work on communication.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Cups02.jpg",
        "affirmation": "I create meaningful connections based on mutual respect.",
        "questions": ["What relationships need nurturing?", "Where is there imbalance in my connections?"],
        "sort_order": 37
      },
      {
        "id": "rws-38",
        "name": "Three of Cups",
        "number": 3,
        "arcana": "minor",
        "suit": "cups",
        "element": "Water",
        "keywords": ["friendship", "celebration", "collaboration"],
        "summary": "Joyful celebration with friends – the happiness of community and shared accomplishments.",
        "interpretation": "Upright, Three of Cups represents friendship, celebration and collaboration. In a therapeutic context, this card encourages you to celebrate with friends and nurture your social connections.",
        "reversed_interpretation": "Reversed, Three of Cups may signal overindulgence, gossip or isolation. Through a therapeutic lens, this reversal invites you to examine whether social activities have become unhealthy or if you have been isolating yourself.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Cups03.jpg",
        "affirmation": "I celebrate life with friends who support me.",
        "questions": ["What friendships need celebrating?", "Am I nurturing my social connections?"],
        "sort_order": 38
      },
      {
        "id": "rws-39",
        "name": "Four of Cups",
        "number": 4,
        "arcana": "minor",
        "suit": "cups",
        "element": "Water",
        "keywords": ["apathy", "contemplation", "disconnection"],
        "summary": "Emotional withdrawal and contemplation – missing opportunities due to discontent or indifference.",
        "interpretation": "Upright, Four of Cups represents apathy, contemplation and disconnection. In a therapeutic context, this card encourages you to examine feelings of boredom or dissatisfaction and consider what might be missing.",
        "reversed_interpretation": "Reversed, Four of Cups may signal new awareness, acceptance or seizing opportunities. Through a therapeutic lens, this reversal invites you to open your eyes to opportunities you may have been ignoring.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Cups04.jpg",
        "affirmation": "I remain open to the opportunities before me.",
        "questions": ["What am I ignoring?", "Why do I feel disconnected?"],
        "sort_order": 39
      },
      {
        "id": "rws-40",
        "name": "Five of Cups",
        "number": 5,
        "arcana": "minor",
        "suit": "cups",
        "element": "Water",
        "keywords": ["loss", "grief", "disappointment"],
        "summary": "Mourning what has been lost while overlooking what remains – the pain of grief and regret.",
        "interpretation": "Upright, Five of Cups represents loss, grief and disappointment. In a therapeutic context, this card encourages you to allow yourself to grieve while also recognizing that not all is lost.",
        "reversed_interpretation": "Reversed, Five of Cups may signal acceptance, moving on or finding peace. Through a therapeutic lens, this reversal invites you to begin the process of healing and focus on what remains.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Cups05.jpg",
        "affirmation": "I honor my grief while remaining open to what remains.",
        "questions": ["What am I grieving?", "What blessings am I overlooking?"],
        "sort_order": 40
      },
      {
        "id": "rws-41",
        "name": "Six of Cups",
        "number": 6,
        "arcana": "minor",
        "suit": "cups",
        "element": "Water",
        "keywords": ["nostalgia", "happy memories", "innocence"],
        "summary": "Sweet memories and childhood innocence – reconnecting with the past and simpler times.",
        "interpretation": "Upright, Six of Cups represents nostalgia, happy memories and innocence. In a therapeutic context, this card encourages you to reconnect with positive memories and the innocence of your inner child.",
        "reversed_interpretation": "Reversed, Six of Cups may signal living in the past, unrealistic memories or moving forward. Through a therapeutic lens, this reversal invites you to examine whether nostalgia is preventing you from living in the present.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Cups06.jpg",
        "affirmation": "I honor my past while living fully in the present.",
        "questions": ["What happy memories nourish me?", "Am I stuck in the past?"],
        "sort_order": 41
      },
      {
        "id": "rws-42",
        "name": "Seven of Cups",
        "number": 7,
        "arcana": "minor",
        "suit": "cups",
        "element": "Water",
        "keywords": ["choices", "fantasy", "illusion"],
        "summary": "Many choices and possibilities – but some may be illusions or wishful thinking.",
        "interpretation": "Upright, Seven of Cups represents choices, fantasy and illusion. In a therapeutic context, this card encourages you to discern between realistic options and wishful thinking.",
        "reversed_interpretation": "Reversed, Seven of Cups may signal clarity, determination or overwhelm. Through a therapeutic lens, this reversal invites you to cut through illusion and make grounded decisions.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Cups07.jpg",
        "affirmation": "I choose wisely from the options before me.",
        "questions": ["What choices are realistic?", "Am I chasing illusions?"],
        "sort_order": 42
      },
      {
        "id": "rws-43",
        "name": "Eight of Cups",
        "number": 8,
        "arcana": "minor",
        "suit": "cups",
        "element": "Water",
        "keywords": ["walking away", "disillusionment", "leaving behind"],
        "summary": "Walking away from what no longer serves you – seeking deeper meaning elsewhere.",
        "interpretation": "Upright, Eight of Cups represents walking away, disillusionment and leaving behind. In a therapeutic context, this card encourages you to have the courage to leave situations that no longer fulfill you.",
        "reversed_interpretation": "Reversed, Eight of Cups may signal fear of change, stagnation or aimless drifting. Through a therapeutic lens, this reversal invites you to examine what is keeping you stuck in unfulfilling situations.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Cups08.jpg",
        "affirmation": "I have the courage to seek what truly fulfills me.",
        "questions": ["What am I ready to leave behind?", "What deeper meaning am I seeking?"],
        "sort_order": 43
      },
      {
        "id": "rws-44",
        "name": "Nine of Cups",
        "number": 9,
        "arcana": "minor",
        "suit": "cups",
        "element": "Water",
        "keywords": ["satisfaction", "emotional fulfillment", "wish granted"],
        "summary": "Emotional satisfaction and wishes fulfilled – the contentment of having what you desire.",
        "interpretation": "Upright, Nine of Cups represents satisfaction, emotional fulfillment and wishes granted. In a therapeutic context, this card encourages you to appreciate the fulfillment of your emotional needs and desires.",
        "reversed_interpretation": "Reversed, Nine of Cups may signal dissatisfaction, materialism or unfulfilled wishes. Through a therapeutic lens, this reversal invites you to examine whether you are pursuing the right things to find true happiness.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Cups09.jpg",
        "affirmation": "I am grateful for the fulfillment of my heart desires.",
        "questions": ["What wishes have been fulfilled?", "What do I truly desire?"],
        "sort_order": 44
      },
      {
        "id": "rws-45",
        "name": "Ten of Cups",
        "number": 10,
        "arcana": "minor",
        "suit": "cups",
        "element": "Water",
        "keywords": ["harmony", "marriage", "happiness", "alignment"],
        "summary": "Complete emotional fulfillment – family harmony and lasting happiness.",
        "interpretation": "Upright, Ten of Cups represents harmony, marriage, happiness and alignment. In a therapeutic context, this card encourages you to appreciate and nurture the harmonious relationships in your life.",
        "reversed_interpretation": "Reversed, Ten of Cups may signal broken relationships, family conflict or misaligned values. Through a therapeutic lens, this reversal invites you to address conflicts that are disrupting family or relationship harmony.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Cups10.jpg",
        "affirmation": "I create and nurture harmony in my relationships.",
        "questions": ["What brings harmony to my relationships?", "Where is there discord to address?"],
        "sort_order": 45
      },
      {
        "id": "rws-46",
        "name": "Page of Cups",
        "number": 11,
        "arcana": "minor",
        "suit": "cups",
        "element": "Water",
        "keywords": ["creative opportunities", "curiosity", "possibility"],
        "summary": "Youthful emotional sensitivity and creative imagination – open to new feelings and ideas.",
        "interpretation": "Upright, Page of Cups represents creative opportunities, curiosity and possibility. In a therapeutic context, this card encourages you to remain open to your emotions and express your creative side.",
        "reversed_interpretation": "Reversed, Page of Cups may signal emotional immaturity, escapism or blocked creativity. Through a therapeutic lens, this reversal invites you to address emotional patterns that are keeping you from maturing.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Cups11.jpg",
        "affirmation": "I remain open to creative and emotional possibilities.",
        "questions": ["What creative opportunity is calling?", "How can I express my emotions more freely?"],
        "sort_order": 46
      },
      {
        "id": "rws-47",
        "name": "Knight of Cups",
        "number": 12,
        "arcana": "minor",
        "suit": "cups",
        "element": "Water",
        "keywords": ["following the heart", "romance", "imagination"],
        "summary": "The romantic dreamer – following the heart with charm and idealistic vision.",
        "interpretation": "Upright, Knight of Cups represents following the heart, romance and imagination. In a therapeutic context, this card encourages you to pursue your dreams with passion while staying grounded.",
        "reversed_interpretation": "Reversed, Knight of Cups may signal moodiness, jealousy or unrealistic expectations. Through a therapeutic lens, this reversal invites you to examine whether romantic idealism is leading to disappointment.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Cups12.jpg",
        "affirmation": "I follow my heart with grounded passion.",
        "questions": ["What is my heart calling me toward?", "Are my expectations realistic?"],
        "sort_order": 47
      },
      {
        "id": "rws-48",
        "name": "Queen of Cups",
        "number": 13,
        "arcana": "minor",
        "suit": "cups",
        "element": "Water",
        "keywords": ["compassion", "calm", "comfort"],
        "summary": "Emotional depth and intuitive wisdom – nurturing others with compassion and understanding.",
        "interpretation": "Upright, Queen of Cups represents compassion, calm and comfort. In a therapeutic context, this card encourages you to nurture yourself and others with emotional wisdom and intuitive care.",
        "reversed_interpretation": "Reversed, Queen of Cups may signal emotional insecurity, codependency or martyrdom. Through a therapeutic lens, this reversal invites you to set healthy emotional boundaries and care for yourself first.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Cups13.jpg",
        "affirmation": "I nurture with compassion while honoring my own needs.",
        "questions": ["How can I offer compassion?", "Am I caring for my own emotional needs?"],
        "sort_order": 48
      },
      {
        "id": "rws-49",
        "name": "King of Cups",
        "number": 14,
        "arcana": "minor",
        "suit": "cups",
        "element": "Water",
        "keywords": ["emotional balance", "control", "generosity"],
        "summary": "Emotional mastery and diplomatic wisdom – leading with heart balanced by reason.",
        "interpretation": "Upright, King of Cups represents emotional balance, control and generosity. In a therapeutic context, this card encourages you to master your emotions and lead with both heart and wisdom.",
        "reversed_interpretation": "Reversed, King of Cups may signal emotional manipulation, moodiness or coldness. Through a therapeutic lens, this reversal invites you to examine whether you are suppressing emotions or using them to manipulate.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Cups14.jpg",
        "affirmation": "I lead with emotional wisdom and balance.",
        "questions": ["How can I better balance emotions and reason?", "Am I emotionally available?"],
        "sort_order": 49
      },
      {
        "id": "rws-50",
        "name": "Ace of Swords",
        "number": 1,
        "arcana": "minor",
        "suit": "swords",
        "element": "Air",
        "keywords": ["breakthrough", "clarity", "new idea"],
        "summary": "Mental clarity and breakthrough – a powerful new idea or moment of truth.",
        "interpretation": "Upright, Ace of Swords represents breakthrough, clarity and new ideas. In a therapeutic context, this card encourages you to embrace mental clarity and use it to cut through confusion.",
        "reversed_interpretation": "Reversed, Ace of Swords may signal confusion, chaos or misuse of power. Through a therapeutic lens, this reversal invites you to find clarity amid confusion and use your intellect wisely.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Swords01.jpg",
        "affirmation": "I embrace clarity and truth in my thinking.",
        "questions": ["What truth is becoming clear?", "How can I cut through confusion?"],
        "sort_order": 50
      },
      {
        "id": "rws-51",
        "name": "Two of Swords",
        "number": 2,
        "arcana": "minor",
        "suit": "swords",
        "element": "Air",
        "keywords": ["difficult decision", "stalemate", "avoidance"],
        "summary": "Facing a difficult choice with blocked emotions – a stalemate requiring decision.",
        "interpretation": "Upright, Two of Swords represents difficult decisions, stalemate and avoidance. In a therapeutic context, this card encourages you to face the decision you have been avoiding.",
        "reversed_interpretation": "Reversed, Two of Swords may signal indecision, confusion or information overload. Through a therapeutic lens, this reversal invites you to work through the paralysis and make a choice.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Swords02.jpg",
        "affirmation": "I face difficult decisions with courage and clarity.",
        "questions": ["What decision am I avoiding?", "What information do I need?"],
        "sort_order": 51
      },
      {
        "id": "rws-52",
        "name": "Three of Swords",
        "number": 3,
        "arcana": "minor",
        "suit": "swords",
        "element": "Air",
        "keywords": ["heartbreak", "suffering", "grief"],
        "summary": "Heartbreak and emotional pain – the sorrow that must be felt to be healed.",
        "interpretation": "Upright, Three of Swords represents heartbreak, suffering and grief. In a therapeutic context, this card encourages you to allow yourself to feel pain so that healing can begin.",
        "reversed_interpretation": "Reversed, Three of Swords may signal recovery, forgiveness or moving on. Through a therapeutic lens, this reversal invites you to begin the healing process and work toward forgiveness.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Swords03.jpg",
        "affirmation": "I allow myself to heal from heartbreak.",
        "questions": ["What pain needs acknowledgment?", "Am I ready to begin healing?"],
        "sort_order": 52
      },
      {
        "id": "rws-53",
        "name": "Four of Swords",
        "number": 4,
        "arcana": "minor",
        "suit": "swords",
        "element": "Air",
        "keywords": ["rest", "restoration", "contemplation"],
        "summary": "Rest and recovery – a period of stillness needed for healing and renewal.",
        "interpretation": "Upright, Four of Swords represents rest, restoration and contemplation. In a therapeutic context, this card encourages you to take time to rest and recover from stress or exhaustion.",
        "reversed_interpretation": "Reversed, Four of Swords may signal restlessness, burnout or stress. Through a therapeutic lens, this reversal invites you to address signs of burnout and prioritize rest.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Swords04.jpg",
        "affirmation": "I give myself permission to rest and recover.",
        "questions": ["What rest do I need?", "Am I ignoring signs of burnout?"],
        "sort_order": 53
      },
      {
        "id": "rws-54",
        "name": "Five of Swords",
        "number": 5,
        "arcana": "minor",
        "suit": "swords",
        "element": "Air",
        "keywords": ["conflict", "tension", "winning at all costs"],
        "summary": "Conflict and defeat – winning battles at the cost of relationships and integrity.",
        "interpretation": "Upright, Five of Swords represents conflict, tension and winning at all costs. In a therapeutic context, this card encourages you to evaluate whether your victories are worth the cost.",
        "reversed_interpretation": "Reversed, Five of Swords may signal reconciliation, making amends or moving on. Through a therapeutic lens, this reversal invites you to make amends and release resentment.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Swords05.jpg",
        "affirmation": "I choose battles that are worth fighting.",
        "questions": ["What conflicts need resolution?", "Is winning worth the cost?"],
        "sort_order": 54
      },
      {
        "id": "rws-55",
        "name": "Six of Swords",
        "number": 6,
        "arcana": "minor",
        "suit": "swords",
        "element": "Air",
        "keywords": ["transition", "leaving behind", "moving on"],
        "summary": "Moving away from difficulty – a transition toward calmer waters and healing.",
        "interpretation": "Upright, Six of Swords represents transition, leaving behind and moving on. In a therapeutic context, this card encourages you to accept help in moving away from difficulties toward a calmer state.",
        "reversed_interpretation": "Reversed, Six of Swords may signal emotional baggage, unresolved issues or resistance. Through a therapeutic lens, this reversal invites you to address what is preventing you from moving forward.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Swords06.jpg",
        "affirmation": "I move forward toward calmer waters.",
        "questions": ["What am I leaving behind?", "What baggage needs releasing?"],
        "sort_order": 55
      },
      {
        "id": "rws-56",
        "name": "Seven of Swords",
        "number": 7,
        "arcana": "minor",
        "suit": "swords",
        "element": "Air",
        "keywords": ["deception", "trickery", "strategy"],
        "summary": "Strategy and stealth – sometimes necessary cunning, but also the shadow of deception.",
        "interpretation": "Upright, Seven of Swords represents deception, trickery and strategy. In a therapeutic context, this card encourages you to examine whether you are being fully honest with yourself and others.",
        "reversed_interpretation": "Reversed, Seven of Swords may signal coming clean, conscience or getting caught. Through a therapeutic lens, this reversal invites you to drop pretenses and address matters openly.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Swords07.jpg",
        "affirmation": "I act with honesty and integrity.",
        "questions": ["Where am I not being honest?", "What truth needs to be spoken?"],
        "sort_order": 56
      },
      {
        "id": "rws-57",
        "name": "Eight of Swords",
        "number": 8,
        "arcana": "minor",
        "suit": "swords",
        "element": "Air",
        "keywords": ["imprisonment", "entrapment", "self-victimization"],
        "summary": "Feeling trapped by circumstances or thoughts – but the bonds are often self-imposed.",
        "interpretation": "Upright, Eight of Swords represents imprisonment, entrapment and self-victimization. In a therapeutic context, this card encourages you to recognize that you may have more options than you believe.",
        "reversed_interpretation": "Reversed, Eight of Swords may signal self-acceptance, new perspective or freedom. Through a therapeutic lens, this reversal invites you to break free from limiting beliefs.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Swords08.jpg",
        "affirmation": "I free myself from self-imposed limitations.",
        "questions": ["What beliefs are trapping me?", "How can I see my situation differently?"],
        "sort_order": 57
      },
      {
        "id": "rws-58",
        "name": "Nine of Swords",
        "number": 9,
        "arcana": "minor",
        "suit": "swords",
        "element": "Air",
        "keywords": ["anxiety", "hopelessness", "nightmares"],
        "summary": "Anxiety and sleepless worry – the dark night of the mind and its racing fears.",
        "interpretation": "Upright, Nine of Swords represents anxiety, hopelessness and nightmares. In a therapeutic context, this card encourages you to reach out for help with your worries rather than suffering in silence.",
        "reversed_interpretation": "Reversed, Nine of Swords may signal hope, reaching out or recovery. Through a therapeutic lens, this reversal invites you to continue seeking support as you emerge from a dark period.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Swords09.jpg",
        "affirmation": "I release my worries and seek support.",
        "questions": ["What keeps me up at night?", "Who can I reach out to for help?"],
        "sort_order": 58
      },
      {
        "id": "rws-59",
        "name": "Ten of Swords",
        "number": 10,
        "arcana": "minor",
        "suit": "swords",
        "element": "Air",
        "keywords": ["painful endings", "deep wounds", "betrayal"],
        "summary": "Rock bottom and painful ending – but also the promise that dawn follows the darkest hour.",
        "interpretation": "Upright, Ten of Swords represents painful endings, deep wounds and betrayal. In a therapeutic context, this card encourages you to accept that something has ended and that healing can begin.",
        "reversed_interpretation": "Reversed, Ten of Swords may signal recovery, regeneration or improvement. Through a therapeutic lens, this reversal invites you to recognize that the worst is over and focus on rebuilding.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Swords10.jpg",
        "affirmation": "I rise from endings with renewed strength.",
        "questions": ["What painful ending must I accept?", "How can I begin to rebuild?"],
        "sort_order": 59
      },
      {
        "id": "rws-60",
        "name": "Page of Swords",
        "number": 11,
        "arcana": "minor",
        "suit": "swords",
        "element": "Air",
        "keywords": ["curiosity", "restlessness", "mental energy"],
        "summary": "Curious and alert mind – eager to learn and communicate, if sometimes scattered.",
        "interpretation": "Upright, Page of Swords represents curiosity, restlessness and mental energy. In a therapeutic context, this card encourages you to channel your mental energy into constructive learning.",
        "reversed_interpretation": "Reversed, Page of Swords may signal deception, manipulation or all talk. Through a therapeutic lens, this reversal invites you to focus your thoughts and communicate with integrity.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Swords11.jpg",
        "affirmation": "I channel my curiosity into meaningful learning.",
        "questions": ["What am I eager to learn?", "Am I communicating clearly?"],
        "sort_order": 60
      },
      {
        "id": "rws-61",
        "name": "Knight of Swords",
        "number": 12,
        "arcana": "minor",
        "suit": "swords",
        "element": "Air",
        "keywords": ["action", "impulsiveness", "defending beliefs"],
        "summary": "Swift action and sharp mind – charging forward with conviction, sometimes too hastily.",
        "interpretation": "Upright, Knight of Swords represents action, impulsiveness and defending beliefs. In a therapeutic context, this card encourages you to take decisive action while being mindful of your delivery.",
        "reversed_interpretation": "Reversed, Knight of Swords may signal no direction, disregard for consequences or unpredictability. Through a therapeutic lens, this reversal invites you to slow down and consider consequences.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Swords12.jpg",
        "affirmation": "I act decisively with awareness of consequences.",
        "questions": ["Am I acting too hastily?", "What am I fighting for?"],
        "sort_order": 61
      },
      {
        "id": "rws-62",
        "name": "Queen of Swords",
        "number": 13,
        "arcana": "minor",
        "suit": "swords",
        "element": "Air",
        "keywords": ["complexity", "perceptiveness", "clear mindedness"],
        "summary": "Clear and perceptive mind – honest truth-telling balanced with compassionate wisdom.",
        "interpretation": "Upright, Queen of Swords represents complexity, perceptiveness and clear-mindedness. In a therapeutic context, this card encourages you to use your insight and experience to make balanced decisions.",
        "reversed_interpretation": "Reversed, Queen of Swords may signal cold-heartedness, cruelty or bitterness. Through a therapeutic lens, this reversal invites you to soften any emotional walls while maintaining healthy boundaries.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Swords13.jpg",
        "affirmation": "I speak truth with clarity and compassion.",
        "questions": ["Am I being honest but kind?", "What past hurt needs healing?"],
        "sort_order": 62
      },
      {
        "id": "rws-63",
        "name": "King of Swords",
        "number": 14,
        "arcana": "minor",
        "suit": "swords",
        "element": "Air",
        "keywords": ["head over heart", "discipline", "truth"],
        "summary": "Intellectual authority and moral clarity – leading with logic, ethics, and clear judgment.",
        "interpretation": "Upright, King of Swords represents head over heart, discipline and truth. In a therapeutic context, this card encourages you to make decisions with clarity and integrity.",
        "reversed_interpretation": "Reversed, King of Swords may signal manipulation, cruelty or weakness. Through a therapeutic lens, this reversal invites you to examine whether you are misusing intellect or being too harsh.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Swords14.jpg",
        "affirmation": "I lead with intellectual clarity and ethical integrity.",
        "questions": ["Am I being fair in my judgments?", "Is my thinking too rigid?"],
        "sort_order": 63
      },
      {
        "id": "rws-64",
        "name": "Ace of Pentacles",
        "number": 1,
        "arcana": "minor",
        "suit": "pentacles",
        "element": "Earth",
        "keywords": ["opportunity", "prosperity", "new venture"],
        "summary": "New material opportunity – the seed of financial or practical success.",
        "interpretation": "Upright, Ace of Pentacles represents opportunity, prosperity and new ventures. In a therapeutic context, this card encourages you to seize practical opportunities for growth and stability.",
        "reversed_interpretation": "Reversed, Ace of Pentacles may signal lost opportunity, missed chance or bad investment. Through a therapeutic lens, this reversal invites you to address feelings of scarcity and look for new opportunities.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Pents01.jpg",
        "affirmation": "I welcome new opportunities for prosperity.",
        "questions": ["What opportunity is presenting itself?", "Am I ready to invest in my future?"],
        "sort_order": 64
      },
      {
        "id": "rws-65",
        "name": "Two of Pentacles",
        "number": 2,
        "arcana": "minor",
        "suit": "pentacles",
        "element": "Earth",
        "keywords": ["balance", "adaptability", "time management"],
        "summary": "Juggling priorities – maintaining balance amid life changing demands.",
        "interpretation": "Upright, Two of Pentacles represents balance, adaptability and time management. In a therapeutic context, this card encourages you to find healthy balance while managing multiple responsibilities.",
        "reversed_interpretation": "Reversed, Two of Pentacles may signal imbalance, disorganization or overwhelm. Through a therapeutic lens, this reversal invites you to simplify and set boundaries when overwhelmed.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Pents02.jpg",
        "affirmation": "I maintain balance while juggling life demands.",
        "questions": ["What needs better balance?", "Can I simplify my commitments?"],
        "sort_order": 65
      },
      {
        "id": "rws-66",
        "name": "Three of Pentacles",
        "number": 3,
        "arcana": "minor",
        "suit": "pentacles",
        "element": "Earth",
        "keywords": ["teamwork", "collaboration", "building"],
        "summary": "Collaborative effort – skilled work that contributes to a greater whole.",
        "interpretation": "Upright, Three of Pentacles represents teamwork, collaboration and building. In a therapeutic context, this card encourages you to value the contributions of others in achieving your goals.",
        "reversed_interpretation": "Reversed, Three of Pentacles may signal lack of teamwork, disorganization or conflict. Through a therapeutic lens, this reversal invites you to address communication issues and work better with others.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Pents03.jpg",
        "affirmation": "I collaborate effectively with others.",
        "questions": ["How can I work better with others?", "What skills can I contribute?"],
        "sort_order": 66
      },
      {
        "id": "rws-67",
        "name": "Four of Pentacles",
        "number": 4,
        "arcana": "minor",
        "suit": "pentacles",
        "element": "Earth",
        "keywords": ["conservation", "security", "control"],
        "summary": "Holding tight to resources – security and stability, but possibly excessive control.",
        "interpretation": "Upright, Four of Pentacles represents conservation, security and control. In a therapeutic context, this card encourages you to examine your relationship with security and letting go.",
        "reversed_interpretation": "Reversed, Four of Pentacles may signal greed, stinginess or possessiveness. Through a therapeutic lens, this reversal invites you to release unhealthy attachments and practice generosity.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Pents04.jpg",
        "affirmation": "I balance security with openness.",
        "questions": ["What am I holding too tightly?", "Can I be more generous?"],
        "sort_order": 67
      },
      {
        "id": "rws-68",
        "name": "Five of Pentacles",
        "number": 5,
        "arcana": "minor",
        "suit": "pentacles",
        "element": "Earth",
        "keywords": ["hardship", "poverty", "isolation"],
        "summary": "Hardship and feeling left out – but help is available for those who seek it.",
        "interpretation": "Upright, Five of Pentacles represents hardship, poverty and isolation. In a therapeutic context, this card encourages you to seek help during difficult times rather than suffering alone.",
        "reversed_interpretation": "Reversed, Five of Pentacles may signal recovery, charity or improvement. Through a therapeutic lens, this reversal invites you to acknowledge positive changes and continue seeking support.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Pents05.jpg",
        "affirmation": "I seek and accept help during difficult times.",
        "questions": ["What support is available to me?", "Am I suffering in silence?"],
        "sort_order": 68
      },
      {
        "id": "rws-69",
        "name": "Six of Pentacles",
        "number": 6,
        "arcana": "minor",
        "suit": "pentacles",
        "element": "Earth",
        "keywords": ["generosity", "charity", "sharing"],
        "summary": "Generosity and fair exchange – giving and receiving in balanced measure.",
        "interpretation": "Upright, Six of Pentacles represents generosity, charity and sharing. In a therapeutic context, this card encourages you to give and receive with balance and gratitude.",
        "reversed_interpretation": "Reversed, Six of Pentacles may signal strings attached, stinginess or imbalance. Through a therapeutic lens, this reversal invites you to examine power dynamics in your giving and receiving.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Pents06.jpg",
        "affirmation": "I give and receive with grace and balance.",
        "questions": ["Is my giving and receiving balanced?", "Are there strings attached?"],
        "sort_order": 69
      },
      {
        "id": "rws-70",
        "name": "Seven of Pentacles",
        "number": 7,
        "arcana": "minor",
        "suit": "pentacles",
        "element": "Earth",
        "keywords": ["patience", "investment", "long-term view"],
        "summary": "Patience and assessment – evaluating progress and waiting for results to mature.",
        "interpretation": "Upright, Seven of Pentacles represents patience, investment and long-term view. In a therapeutic context, this card encourages you to be patient with your progress and trust the process.",
        "reversed_interpretation": "Reversed, Seven of Pentacles may signal impatience, lack of reward or wasted effort. Through a therapeutic lens, this reversal invites you to reassess whether your efforts are well-directed.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Pents07.jpg",
        "affirmation": "I trust in the gradual growth of my efforts.",
        "questions": ["Am I being patient enough?", "Are my efforts well-directed?"],
        "sort_order": 70
      },
      {
        "id": "rws-71",
        "name": "Eight of Pentacles",
        "number": 8,
        "arcana": "minor",
        "suit": "pentacles",
        "element": "Earth",
        "keywords": ["apprenticeship", "skill development", "diligence"],
        "summary": "Dedicated skill-building – the satisfaction of mastering your craft through practice.",
        "interpretation": "Upright, Eight of Pentacles represents apprenticeship, skill development and diligence. In a therapeutic context, this card encourages you to dedicate yourself to learning and self-improvement.",
        "reversed_interpretation": "Reversed, Eight of Pentacles may signal lack of focus, perfectionism or uninspired work. Through a therapeutic lens, this reversal invites you to reconnect with your passion for learning.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Pents08.jpg",
        "affirmation": "I dedicate myself to mastering my craft.",
        "questions": ["What skills am I developing?", "Am I enjoying the learning process?"],
        "sort_order": 71
      },
      {
        "id": "rws-72",
        "name": "Nine of Pentacles",
        "number": 9,
        "arcana": "minor",
        "suit": "pentacles",
        "element": "Earth",
        "keywords": ["self-sufficiency", "luxury", "financial independence"],
        "summary": "Self-sufficiency and abundance – enjoying the fruits of your labor in comfort.",
        "interpretation": "Upright, Nine of Pentacles represents self-sufficiency, luxury and financial independence. In a therapeutic context, this card encourages you to appreciate what you have built and enjoy your achievements.",
        "reversed_interpretation": "Reversed, Nine of Pentacles may signal overworking, superficiality or lack of independence. Through a therapeutic lens, this reversal invites you to find genuine fulfillment beyond material success.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Pents09.jpg",
        "affirmation": "I enjoy the abundance I have created.",
        "questions": ["Can I appreciate what I have achieved?", "Am I truly fulfilled?"],
        "sort_order": 72
      },
      {
        "id": "rws-73",
        "name": "Ten of Pentacles",
        "number": 10,
        "arcana": "minor",
        "suit": "pentacles",
        "element": "Earth",
        "keywords": ["legacy", "inheritance", "family"],
        "summary": "Lasting legacy and family wealth – the culmination of material and family success.",
        "interpretation": "Upright, Ten of Pentacles represents legacy, inheritance and family. In a therapeutic context, this card encourages you to consider the lasting impact you want to have on family and community.",
        "reversed_interpretation": "Reversed, Ten of Pentacles may signal family conflict, financial failure or breaking traditions. Through a therapeutic lens, this reversal invites you to address family issues and define success on your own terms.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Pents10.jpg",
        "affirmation": "I create a legacy of love and abundance.",
        "questions": ["What legacy am I building?", "Are family traditions serving me?"],
        "sort_order": 73
      },
      {
        "id": "rws-74",
        "name": "Page of Pentacles",
        "number": 11,
        "arcana": "minor",
        "suit": "pentacles",
        "element": "Earth",
        "keywords": ["ambition", "diligence", "new financial opportunity"],
        "summary": "Eager learner focused on practical goals – the beginning of material manifestation.",
        "interpretation": "Upright, Page of Pentacles represents ambition, diligence and new financial opportunity. In a therapeutic context, this card encourages you to pursue your practical goals with steady dedication.",
        "reversed_interpretation": "Reversed, Page of Pentacles may signal lack of focus, laziness or missed opportunity. Through a therapeutic lens, this reversal invites you to reconnect with your goals and take practical steps forward.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Pents11.jpg",
        "affirmation": "I pursue my goals with dedicated focus.",
        "questions": ["What practical goals call to me?", "Am I taking consistent action?"],
        "sort_order": 74
      },
      {
        "id": "rws-75",
        "name": "Knight of Pentacles",
        "number": 12,
        "arcana": "minor",
        "suit": "pentacles",
        "element": "Earth",
        "keywords": ["hard work", "productivity", "routine"],
        "summary": "Steady, reliable worker – methodical progress through patience and persistence.",
        "interpretation": "Upright, Knight of Pentacles represents hard work, productivity and routine. In a therapeutic context, this card encourages you to embrace consistency and patience in pursuing your goals.",
        "reversed_interpretation": "Reversed, Knight of Pentacles may signal boredom, laziness or perfectionism. Through a therapeutic lens, this reversal invites you to find sustainable rhythms and avoid burnout.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Pents12.jpg",
        "affirmation": "I make steady progress through consistent effort.",
        "questions": ["Is my pace sustainable?", "Am I being too rigid or too lax?"],
        "sort_order": 75
      },
      {
        "id": "rws-76",
        "name": "Queen of Pentacles",
        "number": 13,
        "arcana": "minor",
        "suit": "pentacles",
        "element": "Earth",
        "keywords": ["nurturing", "practicality", "comfort"],
        "summary": "Nurturing abundance – creating comfort and security through practical wisdom.",
        "interpretation": "Upright, Queen of Pentacles represents nurturing, practicality and comfort. In a therapeutic context, this card encourages you to care for yourself and others in tangible, grounding ways.",
        "reversed_interpretation": "Reversed, Queen of Pentacles may signal self-neglect, materialism or smothering. Through a therapeutic lens, this reversal invites you to balance caring for others with caring for yourself.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Pents13.jpg",
        "affirmation": "I create comfort and nurture with practical love.",
        "questions": ["How can I better care for myself?", "Am I neglecting my practical needs?"],
        "sort_order": 76
      },
      {
        "id": "rws-77",
        "name": "King of Pentacles",
        "number": 14,
        "arcana": "minor",
        "suit": "pentacles",
        "element": "Earth",
        "keywords": ["abundance", "security", "leadership"],
        "summary": "Material mastery and generosity – leading with practical wisdom and abundant resources.",
        "interpretation": "Upright, King of Pentacles represents abundance, security and leadership. In a therapeutic context, this card encourages you to take ownership of your life with confidence and share your abundance.",
        "reversed_interpretation": "Reversed, King of Pentacles may signal greed, materialism or stubbornness. Through a therapeutic lens, this reversal invites you to examine your relationship with wealth and control.",
        "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Pents14.jpg",
        "affirmation": "I lead with practical wisdom and generous abundance.",
        "questions": ["Am I sharing my abundance?", "Is material success my only measure of worth?"],
        "sort_order": 77
      }
    ]
  }'::jsonb,
  NOW(),
  NOW()
);

-- Note: If you need to update instead of insert, first delete the old deck:
-- DELETE FROM user_documents WHERE document_type = 'tarot_deck' AND document_data->>'name' = 'Rider-Waite-Smith Archetypal Tarot';

-- Verify the insert
SELECT id, document_type, is_public,
       document_data->>'name' as deck_name,
       document_data->>'card_count' as card_count
FROM user_documents
WHERE document_type = 'tarot_deck';
